# Logistic Regression

#### Classification of IRIS data set


## Import modules

In [1]:
from sklearn import datasets
from numpy import *
import matplotlib.pyplot as plt
import math
from random import *
from copy import deepcopy

## Data sets

## Logistic Regression

In [2]:
def sigmoid(theta, x):
    h=[] #h : (1*m) vector
    for i in range( len(x) ):
        z = float( dot(x[i],theta) ) #Z : (1*1)number
        h.append( 1.0/(1.0+exp(z)) )
    return h

def gradientDescent(epoch, lr, x, y, initialTheta):
    m,n = shape(x)
    theta = initialTheta

    for j in range(epoch):
        h = mat( sigmoid(theta, x) ).T
        theta = theta + float(lr/m)*x.T*(h-y) ### -로
#         costFunction(x,y,theta)
    return theta


#Logistic Regression Cost Function
def costFunction(x,y,theta): #얘는 사실 할필요 없음. gradientDescent로 구하니까
    h = mat( sigmoid(theta, x) ).T
    j = (-1.0/m) * (log(h).T*y + log(1-h).T*(1-y)) #j:(1x1) number
    print "cost ",(-1.0) * (log(h).T*y + log(1-h).T*(1-y)) #j:(1x1) number
    return float(j)


def predict(test_dat, theta):
    h = sigmoid(theta, test_dat)    
    test_label=[]
    for hp in h:
        test_label.append( round(hp) )
    return test_label

In [3]:
def binToIntLabel(bin_predict_label):
    a, m = shape(bin_predict_label)
    new_predict_label=[-1 for i in range(m)]
    for i in range(m):
        if bin_predict_label[0][i]==1:
            new_predict_label[i] = 0
        if bin_predict_label[1][i]==1:
            new_predict_label[i] = 1
        if bin_predict_label[2][i]==1:
            new_predict_label[i] = 2
        
        if bin_predict_label[0][i]==1 and bin_predict_label[1][i]==1:
            list = [0,1]
            new_predict_label[i] = choice(list) #리스트 중에 랜덤으로선택
        if bin_predict_label[1][i]==1 and bin_predict_label[2][i]==1:
            list = [1,2]
            new_predict_label[i] = choice(list) 
        if bin_predict_label[0][i]==1 and bin_predict_label[2][i]==1:
            list = [0,2]
            new_predict_label[i] = choice(list)
        
        if bin_predict_label[0][i]==1 and bin_predict_label[1][i]==1 and bin_predict_label[2][i]==1:
            list = [0,1,2]
            new_predict_label[i] = choice(list)
    return new_predict_label

def intToBinLabel(train_label, target_label):
    label = deepcopy( train_label) #전체 복사, 주소값 변경 안되도록
    m,n = shape(train_label)
    for i in range(m):
        #target_label만 1, 나머지는 0
        if label[i]==target_label: label[i]=1
        else: label[i]=0
    return label

def divideTrainTest(data, label):
    train_mat=[]; train_label=[]; test_mat=[]; test_label=[]
    for i in range(len(label)):
        #training set(2/3), test set(1/3)
        if i%3==0:
            test_mat.append(data[i])
            test_label.append(label[i])
        else:
            train_mat.append(data[i])
            train_label.append(label[i])
    
    #x0(=1) 추가
    train_mat = concatenate( (train_mat,ones((len(train_mat),1))), axis=1 ) 
    test_mat = concatenate( (test_mat,ones((len(test_mat),1))), axis=1 ) 
    return mat(train_mat), mat(train_label).T, mat(test_mat), test_label

## IRIS data 예제

In [4]:
iris = datasets.load_iris()
train_mat, train_label, test_mat, test_label = divideTrainTest(iris.data, iris.target)

initialTheta = mat([0,0,0,0,0]).T
theta=[]
for i in range(3):
    bin_train_label = intToBinLabel(train_label,i)
    theta.append( gradientDescent(1000, 0.3, train_mat, bin_train_label, initialTheta) )

print "theta0 \n",theta[0], "\n"
print "theta1 \n",theta[1], "\n"
print "theta2 \n",theta[2], "\n"

theta0 
[[-0.68552304]
 [-2.23458994]
 [ 3.57621201]
 [ 1.62620583]
 [-0.45218245]] 

theta1 
[[-2.64313761]
 [ 4.64383865]
 [-0.66876977]
 [ 3.51558321]
 [-1.32462303]] 

theta2 
[[ 3.42074732]
 [ 2.61004525]
 [-4.89664935]
 [-4.08505541]
 [ 1.96585264]] 



In [5]:
bin_predict_label = []
for i in range(3):
    bin_predict_label.append( array(predict(test_mat, theta[i])) )
predict_label = binToIntLabel(bin_predict_label)
print "예측 label\n", predict_label,"\n"
print "실제 label\n", test_label,"\n"
m = len( predict_label )
numOfWrongPredict=0
for i in range(m):
    if predict_label[i] != test_label[i]:
        numOfWrongPredict+=1

print "정확도: ",(m-numOfWrongPredict)*100/m,"%"

예측 label
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, -1, 1, 2, 1, 1, 1, -1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1] 

실제 label
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2] 

정확도:  82 %


## 예제

In [6]:
initialTheta = mat([1,0,0,0]).T #theta(0~n)
x = mat([\
            [0.1, 0.2, 0.1],\
            [10.0, 8.0, 8.0],\
            [0.1, 0.4, 0.1],\
            [9.0, 8.0, 9.0],\
            [0.1, 0.2, 0.4],\
            [8.0, 9.2, 8.1],\
            [0.2, 1.0, 0.6],\
        ])
x = concatenate( (x, ones((len(x),1))), axis=1 ) #add x0 (x0=1)
y = mat([0,1,0,1,0,1,0]).T

theta = gradientDescent(100, 0.05, x, y, initialTheta)


In [7]:
test_dat = mat([\
            [0.1, 0.1, 0.1],\
            [10.0, 7.0, 9.0],\
            [0.1, 0.4, 1],\
            [9.0, 8.0, 7.0]\
            ])
test_dat = concatenate( (test_dat, ones((len(test_dat),1))), axis=1 ) #add x0 (x0=1)
predict(test_dat, theta)

[0.0, 1.0, 0.0, 1.0]